---
title: "Map Log"
author: "Brian Stroh"
date: "November 6, 2018"
output: html_document
runtime: shiny
---

<style type="text/css">
.main-container {
      max-width: 940px;
      margin-left: 0px;
      margin-right: auto;
}
code {
      color: inherit;
      background-color: rgba(0, 0, 0, 0.04);
}
img {
      max-width:100%;
      height: 100%;
}
.tabbed-pane {
      padding-top: 12px;
}
.html-widget {
      margin-bottom: 20px;
}
button.code-folding-btn:focus {
      outline: none;
}

</style>



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(leaflet)
library(dplyr)
library(data.table)
library(urltools)

getLatLong<- function(address){
      if(address$street !="-" && address$city !="-" && address$state !="-" && address$zip !="-"){
            findme<-as.character(paste(address$street,address$city,paste(address$state,paste0(address$zip,"\",null,"),sep=" "),sep=", "))
            address$street<-gsub(" ","+",address$street)
            lookupURL<-paste0("https://www.google.com/maps/place/",address$street,",+",address$city,",+",address$state,"+",address$zip,"/")
      }else if(address$street !="-" && address$city !="-" && address$state !="-"){
            findme<-as.character(paste(address$street,address$city,paste0(address$state,"\",null,"),sep=", "))
            address$street<-gsub(" ","+",address$street)
            lookupURL<-paste0("https://www.google.com/maps/place/",address$street,",+",address$city,",+",address$state,"/")
      }else if(address$city !="-" && address$state !="-"){
            findme<-as.character(paste(address$city,paste0(address$state,"\",null,"),sep=", "))
            lookupURL<-paste0("https://www.google.com/maps/place/",address$city,",+",address$state,"/")
      }else if(address$street !="-"){
            findme<-as.character(paste0(address$street,"\",null,"))
            address$street<-gsub(" ","+",address$street)
            lookupURL<-paste0("https://www.google.com/maps/place/",address$street,"/")
      }else if(address$city !="-"){
            findme<-as.character(paste0(address$city,"\",null,"))
            lookupURL<-paste0("https://www.google.com/maps/place/",address$city,"/")
      }
      download.file(lookupURL,destfile = "rawtext.txt")
      rawtext<-readChar("rawtext.txt", file.info("rawtext.txt")$size)
      pos = regexpr(findme, rawtext)
      newtext<-substring(rawtext,pos+nchar(findme)+11,pos+nchar(findme)+70)
      return(as.numeric(unlist(strsplit(substring(newtext,1,regexpr("]",newtext)-1),","))))
      
      
}

patch_url<-function(my_url){
      ifelse(
            is.na(url_parse(my_url)$scheme), #check if url has something like 'http://'
            my_url<-paste0("http://",my_url), #if not, then add it
            my_url)
}



```


```{r shiny, echo = FALSE, fig.pos='left'}
#Notes for future development:
      #Look here for resetting inputs: https://stackoverflow.com/questions/24265980/reset-inputs-button-in-shiny-app
      #Can't use uploaded picture as icon with R, but probably with HTML/JS
      #In order to really make useful, would need to set up a database with a user login that stores inputs
      #Would also need to add functionality to delete rows
      #Also need to force the links to open in a new tab so that they don't kill the shiny app when in the browser

ui <- fluidPage(pageWithSidebar(
            headerPanel(""),
            sidebarPanel(
                    textInput("label","Address Label","-"),
                    textInput("street","Street Address","-"),
                    textInput("city","City","-"),
                    textInput("state","State","-"),
                    textInput("zip","Zip Code","-"),
                    textInput("url","HyperLink","-"),
      #Might add later              fileInput("icon", "Choose Pictures", multiple = FALSE,accept = c("image/gif","image/jpeg","image/png","image/tiff","image/svg+xml")),
                    actionButton("add", "Add Location")
              ),
            mainPanel(
                  tabsetPanel(
                        tabPanel("Current Logged Locations",
                                leafletOutput("map")
                        ),
                        tabPanel("Logged Location Table",
                                dataTableOutput("address_table")
                        )
                  )
            )
))
server <- function(input, output, session) {
      test_cells <- 5
      my_addresses <- reactiveValues()
      my_addresses$data <- data.table(label = rep("-",test_cells),
                                      street = rep("-",test_cells),
                                      city = rep("-",test_cells),
                                      state = rep("-",test_cells),
                                      zip = rep("-",test_cells),
                                      url = rep("-",test_cells),
                                      icon = rep("http://pluspng.com/img-png/trollface-png-troll-face-png-image-19697-900.png",test_cells),
                                      longitude= rnorm(test_cells) - 122.5, #Hidden Field
                                      latitude = rnorm(test_cells) + 47, #Hidden Field
                                      link = as.character(rep("<a href='http://www.google.com/'>Example Link(Google)</a>",test_cells))) #Hidden Field
      
        mydf <- reactive({
              my_addresses$data
        })
        
        observeEvent(input$add,{
            if (input$street!="-"||input$city!="-"){
                  currLatLong<- getLatLong(data.frame(street = input$street,
                                                          city = input$city,
                                                          state = input$state,
                                                          zip = input$zip))
#icon debug       cat(file=stderr(),"icon:",unlist(input$icon),"testing if length(input$icon$name)==0",length(input$icon$name)==0,"/n")
#icon debug       selectedIcon<-ifelse(length(input$icon$name)==0,"http://pluspng.com/img-png/trollface-png-troll-face-png-image-19697-900.png",input$icon$name)
                  new_row=data.frame(
                        label = input$label,
                        street = input$street,
                        city = input$city,
                        state = input$state,
                        zip = input$zip,
                        url = input$url,
                        icon = "http://pluspng.com/img-png/trollface-png-troll-face-png-image-19697-900.png",
                              #selectedIcon,
                        longitude=currLatLong[2],
                        latitude=currLatLong[1],
                        link=paste0("<a href='",patch_url(input$url),"'>",input$label,"</a>"))
            }
            my_addresses$data<-rbind(mydf(),new_row)
        })
        
        
        output$map <- renderLeaflet({
            leaflet() %>%
                  addTiles() %>%
                  addMarkers(data = select(mydf(),latitude,longitude), 
                             icon = makeIcon(iconUrl = mydf()$icon,
                                    iconWidth = 40, iconHeight = 40,
                                    iconAnchorX = 15, iconAnchorY = 15),
                             popup = mydf()$link,
                             clusterOptions = markerClusterOptions())
        })
        
        
        output$address_table<-renderDataTable(select(mydf(),-c(longitude, latitude, link)))
              
      }

shinyApp(ui, server, options = list(height = 600, width =1400))
```

**In each popup link, be sure to right click and open in a new tab/window.**  
*Please close this page when you are finished.*